[features]
seeds = false
[programs.localnet]
clad = "GH4aPZ5bXQr3MhN6MrejxKLTj6gUdyrGZvieagrfA3ke"
[programs.devnet]
clad = "GH4aPZ5bXQr3MhN6MrejxKLTj6gUdyrGZvieagrfA3ke"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/clad/tests/anchor/*.ts"
create-pool = "ts-node scripts/src/create-pool.ts"
create-lp = "ts-node scripts/src/create-liquidity-position.ts"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "scripts/accounts/usdc.json"
