[features]
seeds = false
[programs.localnet]
clad = "GH4aPZ5bXQr3MhN6MrejxKLTj6gUdyrGZvieagrfA3ke"
[programs.devnet]
clad = "GH4aPZ5bXQr3MhN6MrejxKLTj6gUdyrGZvieagrfA3ke"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/clad/tests/anchor/*.ts"

# TODO: use tsconfig.json in `scripts` directory to use `@/` alias for `scripts/src` directory files
1-create-pool = "ts-node -p scripts/src/create-pool.ts"
2-create-lp = "ts-node -p scripts/src/create-liquidity-position.ts"
3-do-swap = "ts-node -p scripts/src/do-swap.ts"
4-open-trade = "ts-node -p scripts/src/open-trade-position.ts"

# For cloning addresses
[test.validator]
url = "https://api.mainnet-beta.solana.com"

# Jupiter
[[test.validator.clone]]
address = "JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB"

# Modified USDC (mint authority set to local user)
[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "scripts/accounts/usdc.json"
